language: node_js
node_js:
  - "stable"
  - "5.4.1"
git:
  depth: 1
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API_KEY
  on:
    branch: master
    node: "5.4.1"
